Onco_data/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetView
from django.views.generic import TemplateView
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('data/', include('data.urls')),
    path('password-reset/', PasswordResetView.as_view(
        template_name='registration/password-reset.html'), name='password_reset'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password_reset_complete'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

account/urls.py
from django.urls import path

from account import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('my_profile/<int:pk>/', views.MyProfile.as_view(), name='my_profile'),
    path('password_change/<int:pk>/', views.ChangePassword.as_view(), name='password_change'),
    path('sign-up/', views.SignUp.as_view(), name='sign-up'),

]

data/urls.py
from django.urls import path

from data import views


app_name = 'data'


urlpatterns = [
    path('clinical_research/', views.ClinicalResearch.as_view(), name='clinical_research'),
    path('clinic_data/<int:pk>', views.ClinicalData.as_view(), name='clinic_data'),
    # path('download-xlsx/', views.RateDownloadXLSX.as_view(), name='download-xlsx'),
    path('add_clinic/', views.AddClinic.as_view(), name='add_clinic'),
    path('edit_clinic/<int:pk>', views.EditClinic.as_view(), name='edit_clinic'),
    path('delete_clinic/<int:pk>', views.DeleteClinic.as_view(), name='delete_clinic'),
]

data/models.py
from django.db import models

from data import model_choices as mch


# class Team(models.Model):
#    # doctors_name = models.CharField(max_length=128)
#    # access = models.PositiveIntegerField(choices=mch.research_roles)

#    # def __unicode__(self):
#        # return "".join(self.doctors_name, " | ", self.access)


# class Patient(models.Model):
#    # patients_name = models.CharField(max_length=128)
#    # status = models.PositiveIntegerField(choices=mch.research_status)

#    # def __unicode__(self):
#        # return "".join(self.patients_name, " | ", self.status)


# class Fop(models.Model):
#    fop_name = models.CharField(max_length=128)

#    # def save(self, *args, **kwargs):
#       # super().save(*args, **kwargs)


class Clinic(models.Model):
    # Clinical research
    research_name = models.CharField(max_length=256)
    patients_profile = models.CharField(max_length=256)
    date_condition = models.DateTimeField()
    protocol_date = models.CharField(max_length=128)  # дата и номер протокола ДФЦ утверждения
    PI = models.PositiveIntegerField(choices=mch.PI_mentors)
    # Clinical data
    sponsor = models.CharField(max_length=256)
    begin_date = models.DateTimeField()

    # fop = models.ManyToManyField(Fop)  # FOP data
    monitor = models.CharField(max_length=256)
    first_patient = models.DateTimeField()  # date of registration of the first patient
    # Team data
    # team = models.ManyToManyField(Team)
    name_doctor_field = models.CharField(max_length=512)  # name with access to research
    # Patient data
    # patient = models.ManyToManyField(Patient)
    patients_name_status = models.CharField(max_length=512)  # Patients and their current status
    sae = models.CharField(max_length=512)
    # Update sign date for monitoring
    update = models.DateTimeField(auto_now_add=True)
    f_o_p_data = models.CharField(max_length=256)


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

data/forms.py
from django import forms
from data.models import Clinic


class AddClinicForm(forms.ModelForm):

    class Meta:
        model = Clinic
        field = (
            'research_name', 'patients_profile', 'date_condition', 'protocol_date', 'PI', 'sponsor', 'begin_date',
            'monitor', 'first_patient', 'name_doctor_field', 'patients_name_status', 'sae', 'f_o_p_data',
        )

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.save()

        return instance

data/views.py
from django.http import HttpResponse  # noqa
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, UpdateView, CreateView

from data.models import Clinic  # ClinicData, Team, Patient
from data import model_choices as mch  # noqa


class ClinicalResearch(ListView):
    paginate_by = 50
    queryset = Clinic.objects.all()
    template_name = 'research-list.html'


class ClinicalData(ListView):
    queryset = Clinic.objects.all()
    template_name = 'clinic-data.html'


class EditClinic(UpdateView):
    template_name = 'edit-data.html'
    model = Clinic
    fields = 'research_name', 'patients_profile', 'date_condition', 'protocol_date', 'PI', 'sponsor', 'begin_date', \
             'monitor', 'first_patient', 'name_doctor_field', 'patients_name_status', 'sae', 'f_o_p_data'
    success_url = reverse_lazy('data:clinical_research')


class DeleteClinic(DeleteView):
    model = Clinic
    success_url = reverse_lazy('data:clinical_research')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


class AddClinic(CreateView):
    template_name = 'clinic_form.html'
    model = Clinic
    fields = 'research_name', 'patients_profile', 'date_condition', 'protocol_date', 'PI', 'sponsor', 'begin_date', \
             'monitor', 'first_patient', 'name_doctor_field', 'patients_name_status', 'sae', 'f_o_p_data'
    success_url = reverse_lazy('data:clinical_research')

data/templates/clinic-data.html
{% extends 'base.html' %}

{% block title %} Clinical Data {% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
    <table class="table table-dark">

  <thead>
    <tr>
      <th scope="col">Спонсор</th>
      <th scope="col">Дата старта</th>
      <th scope="col">ФОПы</th>
      <th scope="col">Монитор</th>
      <th scope="col">Дата первого пациента</th>
      <th scope="col">Врачи|Доступы</th>
      <th scope="col">Пациенты|Статус</th>
      <th scope="col">SAE</th>
    </tr>
  </thead>
  <tbody>
  {% for data in object_list %}
    <tr>
      <th scope="row">{{ data.sponsor }}</th>
      <td>{{ data.begin_date }}</td>
      <td>{{ data.f_o_p_data }}</td>
      <td>{{ data.monitor }}</td>
      <td>{{ data.first_patient }}</td>
      <td>{{ data.name_doctor_field }}</td>
      <td>{{ data.patients_name_status }}</td>
      <td>{{ data.sae }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% else %}
    <div class="alert alert-dark" role="alert">
  Добрый день! Необходимо <a href="{% url 'account:login' %}" class="alert-link">авторизироваться</a>, чтобы пользоваться сервисом.
    </div>
    {% endif %}
{% endblock content %}

data/templates/clinic_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Add Data{% endblock title %}

{% block content %}
    <br><div class="d-flex justify-content-center border border-dark rounded">Добавить Исследование</div><br>
 	<form method="post">
        {% csrf_token %}
 		{{ form|crispy }}
 		<button class="btn btn-dark" type="submit">Сохранить</button>
 	</form>
{% endblock content %}

data/templates/edit-data.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Edit Data{% endblock title %}

{% block content %}
    <br><div class="d-flex justify-content-center border border-dark rounded">Edit data</div><br>
 	<form method="post">
        {% csrf_token %}
 		{{ form|crispy }}
 		<button class="btn btn-dark" type="submit">Save</button>
 	</form>
{% endblock content %}

data/templates/research-list.html
{% extends 'base.html' %}

{% block title %} Clinical Research {% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
    <a href="{% url 'data:add_clinic' %}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Добавить Исследование</a>
    <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Исследования</th>
      <th scope="col">Профиль пациентов</th>
      <th scope="col">Дата начала</th>
      <th scope="col">Дата и номер протокола ДФЦ</th>
      <th scope="col">PI</th>
      <th scope="col">Последние изменения</th>

    </tr>
  </thead>
  <tbody>
  {% for data in object_list %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><a href="{% url 'data:clinic_data' pk=data.id %}" class="badge badge-light">{{ data.research_name }}</a></td>
      <td>{{ data.patients_profile }}</td>
      <td>{{ data.date_condition }}</td>
      <td>{{ data.protocol_date }}</td>
      <td>{{ data.PI }}</td>
      <td>{{ data.update }}</td>
      <td><a class="btn btn-dark" href="{% url 'data:edit_clinic' pk=data.id %}">Изменить</a></td>
        <td><a class="btn btn-dark" href="{% url 'data:delete_clinic' pk=data.id %}">Удалить</a></td>

    </tr>
  {% endfor %}
  </tbody>
</table>
    {% else %}
    <div class="alert alert-dark" role="alert">
  Добрый день! Необходимо <a href="{% url 'account:login' %}" class="alert-link">авторизироваться</a>, чтобы пользоваться сервисом.
    </div>
    {% endif %}

{% endblock content %}