Onco_data/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetView
from django.views.generic import TemplateView
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('data/', include('data.urls')),
    path('password-reset/', PasswordResetView.as_view(
        template_name='registration/password-reset.html'), name='password_reset'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password_reset_complete'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

account/urls.py
from django.urls import path

from account import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'account'


urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('my_profile/<int:pk>/', views.MyProfile.as_view(), name='my_profile'),
    path('password_change/<int:pk>/', views.ChangePassword.as_view(), name='password_change'),
    path('sign-up/', views.SignUp.as_view(), name='sign-up'),

]

data/urls.py
from django.urls import path

from data import views


app_name = 'data'


urlpatterns = [
    path('clinical_research/', views.ClinicalResearch.as_view(), name='clinical_research'),
    path('clinic_data/<int:pk>', views.ClinicalData.as_view(), name='clinic_data'),
    # path('download-xlsx/', views.RateDownloadXLSX.as_view(), name='download-xlsx'),
    path('add_clinic/', views.AddClinic.as_view(), name='add_clinic'),
    path('edit_clinic/<int:pk>', views.EditClinic.as_view(), name='edit_clinic'),
    path('delete_clinic/<int:pk>', views.DeleteClinic.as_view(), name='delete_clinic'),
]

templates/parts/navbar.html
{% load active_tab %}


<nav class="navbar navbar-dark bg-dark">
    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'index' %}">Начало</a>

    <a class="navbar-brand" href="{% url 'data:clinical_research' %}">Исследования</a>
    {% else %}
    <a class="navbar-brand" href="{% url 'index' %}">Добро пожаловать</a>

    <a class="navbar-brand" href="{% url 'data:clinical_research' %}">Исследования</a>

    <a class="navbar-brand" href="{% url 'account:login' %}">Войти</a>
    {% endif %}
 	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
 		<span class="navbar-toggler-icon"></span>
 	</button>

 	<div class="collapse navbar-collapse" id="navbarText">
 		<ul class="navbar-nav mr-auto">
 			<li class="nav-item {{ request.path|active:'index' }}">
 				<a class="nav-link" href="{% url 'index' %}">Домой</a>
 			</li>
 			{% if request.user.is_authenticated %}
 				<li class="nav-item">
 					<a class="nav-link" href="{% url 'account:my_profile' request.user.id %}">Мой профиль</a>
 				</li>
                <li class="nav-item">
 					<a class="nav-link" href="{% url 'account:sign-up' %}">Создать профиль</a>
 				</li>
 				<li class="nav-item">
 					<a class="nav-link" href="{% url 'account:logout' %}">Выйти</a>
 				</li>
 			{% else %}
 				<li class="nav-item">
 					<a class="nav-link" href="{% url 'account:login' %}">Войти</a>
 				</li>
 			{% endif %}
 		</ul>
 	</div>
</nav>